#!/bin/dash

xset +fp ${HOME}/.fonts
xset fp rehash

compton -c -f -C -F -D 20 -I 0.1 -O 0.1 &

# Keyboard switch layout on Shift+CapsLock
setxkbmap -rules evdev -model pc105 -layout us,ru -option -option "grp:shift_caps_toggle" &
# Authentication
/usr/lib/polkit-gnome-authentication-agent-1 &
# Battery level
xbattbar -a -c -i#005577 -o#222222 &
# Wallpaper
feh --bg-fill ${HOME}/Pictures/wall.jpg &
# Cursor icon
xsetroot -cursor_name left_ptr &

# Lemonbar
. ${PANEL_CONFIG_PATH}/panel_colors
${PANEL_CONFIG_PATH}/panel &

# Update volume indicator
${BSPWM_SCRIPTS_PATH}/volume.sh get &

# Tray
# stalonetray -t true -geometry 1x1-175+0 &

# Hotkey daemon
sxhkd &

bspc monitor -d A B C

bspc config focused_border_color    "${COLOR_STATE_FG}"
bspc config presel_feedback_color   "${COLOR_STATE_FG}"

bspc config border_width            2
bspc config window_gap              12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config click_to_focus          true

bspc rule -a Gimp state=floating follow=on

bspc config top_padding             0

# Floating layout by default
# bspc rule -a '*' state=floating
