#! /bin/sh

xcompmgr &
# Keyboard switch layout on Shift+CapsLock
setxkbmap -rules evdev -model pc105 -layout us,ru -option -option "grp:shift_caps_toggle" &
# Authentication
/usr/lib/polkit-gnome-authentication-agent-1 &
# Battery level
xbattbar -a -c -i#005577 -o#222222 &
# Wallpaper
feh --bg-fill /home/raandoom/Pictures/wall.jpg &
# Cursor icon
xsetroot -cursor_name left_ptr &

# We prepend /usr/share/gnome since its defaults.list actually points 
# to /etc so it is configurable.
if [ -z "$XDG_DATA_DIRS" ]; then
    XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share/:/usr/share/
else
    XDG_DATA_DIRS=/usr/share/gnome:"$XDG_DATA_DIRS"
fi
export XDG_DATA_DIRS

# Lemonbar
. ${PANEL_CONFIG_PATH}/panel_colors
${PANEL_CONFIG_PATH}/panel &

# Tray
# stalonetray -t true -geometry 1x1-175+0 &

# Hotkey daemon
sxhkd &

bspc monitor -d A B C

bspc config focused_border_color    "${COLOR_STATE_FG}"
bspc config presel_feedback_color   "${COLOR_STATE_FG}"

bspc config border_width            2
bspc config window_gap              12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config click_to_focus          true

bspc rule -a Gimp state=floating follow=on

bspc config top_padding             0
